### ISSUE TITLE
Impossible to override gestureRecognizer shouldRecognizeSimultaneouslyWith method when pod is added

### ISSUE THREAD

**Issue by KellyBennett** [teambition/TBEmptyDataSet#10]
`public func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool`

needs to be

'open func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool'

because you can't override methods that aren't in the same module.

**Comment by hongxinhope** [comment]
Thanks for feedback!
