### ISSUE TITLE
Hide method-swizzling logs

### ISSUE THREAD

**Issue by podratz** [teambition/TBEmptyDataSet#12]
This is the output to my console.
```
tb_swizzleTableViewReloadData
tb_swizzleTableViewEndUpdates
tb_swizzleCollectionViewReloadData
tb_swizzleCollectionViewPerformBatchUpdates
```
Did you consider to hide these logs when the library is integrated as a dependency?
I'm using Cocoapods and would really appreciate not to see these lines every time I open my app.
Thanks for your great work.

**Comment by hongxinhope** [comment]
@nickpodratz Many thanks, the logs has been removed in [release 2.5](https://github.com/teambition/TBEmptyDataSet/releases/tag/2.5).
