### ISSUE TITLE
iPhone X support

### ISSUE THREAD

**Issue by anushkmittal** [teambition/TBEmptyDataSet#16]
The text goes off center

**Comment by anushkmittal** [comment]
![simulator screen shot - siri_x - 2017-09-20 at 03 35 53](https://user-images.githubusercontent.com/13961658/30632081-d2ac7d22-9db4-11e7-8017-7af350bdd0f8.png)

**Comment by anushkmittal** [comment]
#15 fixes it. Thanks for the PR @kazutoyo-picapp

**Comment by hongxinhope** [comment]
@anushkmittal Thank you for feedback, this issue was fixed in [release 2.6](https://github.com/teambition/TBEmptyDataSet/releases/tag/2.6).
