### ISSUE TITLE
Remove Empty Set When Reloading Table Sections

### ISSUE THREAD

**Issue by jonathansolorzn** [teambition/TBEmptyDataSet#17]
To animate my table view reload I use the following code:

            let range = NSMakeRange(0, self.tableView.numberOfSections)
            let sections = NSIndexSet(indexesIn: range)
            self.tableView.reloadSections(sections as IndexSet, with: .automatic)

But the image and text for the empty state stays on the screen when data is reloaded, How could I solve it? It works only with `tableView.reloadData()`

**Comment by monmond** [comment]
@felixsolorzano collectionView.updateEmptyDataSetIfNeeded()
