### ISSUE TITLE
verticalSpaceForEmptyDataSet return nagative value crash

### ISSUE THREAD

**Issue by StormXX** [teambition/TBEmptyDataSet#5]

**Comment by hongxinhope** [comment]
Many thanks for your feedback!

This problem is fixed in [release 1.6](https://github.com/teambition/TBEmptyDataSet/releases/tag/1.6), and it supports multiple vertical spaces now, you can use `func verticalSpacesForEmptyDataSet(scrollView: UIScrollView!) -> [CGFloat]`.

Enjoy yourself!
