### ISSUE TITLE
Cocoapods still on 1.8

### ISSUE THREAD

**Issue by samvanh** [teambition/TBEmptyDataSet#9]
Cocoapods still has 1.8 as newest version

**Comment by talisk** [comment]
+1

**Comment by ghost** [comment]
Agreed. not compatible with swift3 when using cocoapods

**Comment by hongxinhope** [comment]
Thanks for feedback, CocoaPods is supported in [release 2.3](https://github.com/teambition/TBEmptyDataSet/releases/tag/2.3).
